import { Patient } from "@/components/Fihr/models";

export const mockPatients: Patient = [
  {
    resourceType: "Patient",
    id: "2558321",
    meta: {
      versionId: "1",
      lastUpdated: "2021-09-20T18:55:21.487+00:00",
      source: "#0jnoaDraceCyzkVN",
    },
    text: {
      status: "generated",
      div: '<div xmlns="http://www.w3.org/1999/xhtml"><div class="hapiHeaderText">John <b>FHIR </b></div><table class="hapiPropertyTable"><tbody><tr><td>Identifier</td><td>12345678</td></tr><tr><td>Address</td><td><span>109 ClinicalLink Circle </span><br/><span>Clinton </span><span>MS </span></td></tr><tr><td>Date of birth</td><td><span>08 November 2002</span></td></tr></tbody></table></div>',
    },
    identifier: [
      {
        system: "http://centralsquare.com/mrn",
        value: "12345678",
      },
    ],
    name: [
      {
        family: "Fhir",
        given: ["John"],
      },
    ],
    gender: "male",
    birthDate: "2002-11-08",
    address: [
      {
        line: ["109 ClinicalLink Circle"],
        city: "Clinton",
        state: "MS",
        postalCode: "39056",
      },
    ],
  },
  {
    resourceType: "Patient",
    id: "6f811a24-99ee-481d-9f80-e629958f85d9",
    meta: {
      versionId: "1",
      lastUpdated: "2020-03-24T18:31:08.398+00:00",
      source: "#xpDJndYcDbjut16w",
      profile: [
        "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient",
      ],
      tag: [
        {
          system: "https://smarthealthit.org/tags",
          code: "Covid19 synthetic population from Synthea",
        },
      ],
    },
    text: {
      status: "generated",
      div: '<div xmlns="http://www.w3.org/1999/xhtml">Generated by <a href="https://github.com/synthetichealth/synthea">Synthea</a>.Version identifier: 2177cffc\n .   Person seed: -5695127293569717619  Population seed: 12345</div>',
    },
    extension: [
      {
        url: "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
        extension: [
          {
            url: "ombCategory",
            valueCoding: {
              system: "urn:oid:2.16.840.1.113883.6.238",
              code: "2106-3",
              display: "White",
            },
          },
          {
            url: "text",
            valueString: "White",
          },
        ],
      },
      {
        url: "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
        extension: [
          {
            url: "ombCategory",
            valueCoding: {
              system: "urn:oid:2.16.840.1.113883.6.238",
              code: "2186-5",
              display: "Not Hispanic or Latino",
            },
          },
          {
            url: "text",
            valueString: "Not Hispanic or Latino",
          },
        ],
      },
      {
        url: "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
        valueString: "Geralyn932 Hansen121",
      },
      {
        url: "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
        valueCode: "M",
      },
      {
        url: "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
        valueAddress: {
          city: "Skokie",
          state: "Illinois",
          country: "US",
        },
      },
      {
        url: "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
        valueDecimal: 0,
      },
      {
        url: "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
        valueDecimal: 15,
      },
    ],
    identifier: [
      {
        system: "https://github.com/synthetichealth/synthea",
        value: "e81e9d96-7eb1-496b-aebb-125ccfd502c8",
      },
      {
        type: {
          coding: [
            {
              system: "http://terminology.hl7.org/CodeSystem/v2-0203",
              code: "MR",
              display: "Medical Record Number",
            },
          ],
          text: "Medical Record Number",
        },
        system: "http://hospital.smarthealthit.org",
        value: "e81e9d96-7eb1-496b-aebb-125ccfd502c8",
      },
      {
        type: {
          coding: [
            {
              system: "http://terminology.hl7.org/CodeSystem/v2-0203",
              code: "SS",
              display: "Social Security Number",
            },
          ],
          text: "Social Security Number",
        },
        system: "http://hl7.org/fhir/sid/us-ssn",
        value: "999-26-6748",
      },
      {
        type: {
          coding: [
            {
              system: "http://terminology.hl7.org/CodeSystem/v2-0203",
              code: "DL",
              display: "Driver's License",
            },
          ],
          text: "Driver's License",
        },
        system: "urn:oid:2.16.840.1.113883.4.3.25",
        value: "S99973152",
      },
    ],
    name: [
      {
        use: "official",
        family: "Stamm704",
        given: ["Brady998"],
      },
    ],
    telecom: [
      {
        system: "phone",
        value: "555-382-5259",
        use: "home",
      },
    ],
    gender: "male",
    birthDate: "2004-02-15",
    address: [
      {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/geolocation",
            extension: [
              {
                url: "latitude",
                valueDecimal: 41.83765723849765,
              },
              {
                url: "longitude",
                valueDecimal: -87.50691014178062,
              },
            ],
          },
        ],
        line: ["826 Farrell Mission"],
        city: "Chicago",
        state: "IL",
        postalCode: "60007",
        country: "US",
      },
    ],
    maritalStatus: {
      coding: [
        {
          system: "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
          code: "S",
          display: "Never Married",
        },
      ],
      text: "Never Married",
    },
    multipleBirthBoolean: false,
    communication: [
      {
        language: {
          coding: [
            {
              system: "urn:ietf:bcp:47",
              code: "en-US",
              display: "English",
            },
          ],
          text: "English",
        },
      },
    ],
  },
  {
    resourceType: "Patient",
    id: "526591c9-949c-429a-8f57-a2d790f73ee6",
    meta: {
      versionId: "1",
      lastUpdated: "2020-03-24T21:23:17.599+00:00",
      source: "#2a73nsRzadoNGyKh",
      profile: [
        "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient",
      ],
      tag: [
        {
          system: "https://smarthealthit.org/tags",
          code: "Covid19 synthetic population from Synthea",
        },
      ],
    },
    text: {
      status: "generated",
      div: '<div xmlns="http://www.w3.org/1999/xhtml">Generated by <a href="https://github.com/synthetichealth/synthea">Synthea</a>.Version identifier: 7ff8db58\n .   Person seed: -8941470304838382841  Population seed: 12345</div>',
    },
    extension: [
      {
        url: "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
        extension: [
          {
            url: "ombCategory",
            valueCoding: {
              system: "urn:oid:2.16.840.1.113883.6.238",
              code: "2106-3",
              display: "White",
            },
          },
          {
            url: "text",
            valueString: "White",
          },
        ],
      },
      {
        url: "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
        extension: [
          {
            url: "ombCategory",
            valueCoding: {
              system: "urn:oid:2.16.840.1.113883.6.238",
              code: "2186-5",
              display: "Not Hispanic or Latino",
            },
          },
          {
            url: "text",
            valueString: "Not Hispanic or Latino",
          },
        ],
      },
      {
        url: "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
        valueString: "Rosamaria757 Dooley940",
      },
      {
        url: "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
        valueCode: "F",
      },
      {
        url: "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
        valueAddress: {
          city: "Corona",
          state: "California",
          country: "US",
        },
      },
      {
        url: "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
        valueDecimal: 0,
      },
      {
        url: "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
        valueDecimal: 60,
      },
    ],
    identifier: [
      {
        system: "https://github.com/synthetichealth/synthea",
        value: "dae58577-51b7-41ca-b967-8051d5dedb6c",
      },
      {
        type: {
          coding: [
            {
              system: "http://terminology.hl7.org/CodeSystem/v2-0203",
              code: "MR",
              display: "Medical Record Number",
            },
          ],
          text: "Medical Record Number",
        },
        system: "http://hospital.smarthealthit.org",
        value: "dae58577-51b7-41ca-b967-8051d5dedb6c",
      },
      {
        type: {
          coding: [
            {
              system: "http://terminology.hl7.org/CodeSystem/v2-0203",
              code: "SS",
              display: "Social Security Number",
            },
          ],
          text: "Social Security Number",
        },
        system: "http://hl7.org/fhir/sid/us-ssn",
        value: "999-18-6462",
      },
      {
        type: {
          coding: [
            {
              system: "http://terminology.hl7.org/CodeSystem/v2-0203",
              code: "DL",
              display: "Driver's License",
            },
          ],
          text: "Driver's License",
        },
        system: "urn:oid:2.16.840.1.113883.4.3.25",
        value: "S99951501",
      },
      {
        type: {
          coding: [
            {
              system: "http://terminology.hl7.org/CodeSystem/v2-0203",
              code: "PPN",
              display: "Passport Number",
            },
          ],
          text: "Passport Number",
        },
        system:
          "http://standardhealthrecord.org/fhir/StructureDefinition/passportNumber",
        value: "X66519165X",
      },
    ],
    name: [
      {
        use: "official",
        family: "Fay398",
        given: ["Janie347"],
        prefix: ["Mrs."],
      },
      {
        use: "maiden",
        family: "Parker433",
        given: ["Janie347"],
        prefix: ["Mrs."],
      },
    ],
    telecom: [
      {
        system: "phone",
        value: "555-505-3473",
        use: "home",
      },
    ],
    gender: "female",
    birthDate: "1910-03-12",
    deceasedDateTime: "1971-10-05T20:26:46-05:00",
    address: [
      {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/geolocation",
            extension: [
              {
                url: "latitude",
                valueDecimal: 34.081983406756144,
              },
              {
                url: "longitude",
                valueDecimal: -118.25669397293719,
              },
            ],
          },
        ],
        line: ["610 Sipes Approach"],
        city: "Los Angeles",
        state: "CA",
        country: "US",
      },
    ],
    maritalStatus: {
      coding: [
        {
          system: "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
          code: "M",
          display: "M",
        },
      ],
      text: "M",
    },
    multipleBirthBoolean: false,
    communication: [
      {
        language: {
          coding: [
            {
              system: "urn:ietf:bcp:47",
              code: "en-US",
              display: "English",
            },
          ],
          text: "English",
        },
      },
    ],
  },
  {
    resourceType: "Patient",
    id: "1202215",
    meta: {
      versionId: "1",
      lastUpdated: "2020-06-12T16:43:17.335+00:00",
      source: "#C9ijbIkcDxgY3Hdt",
    },
    text: {
      status: "generated",
      div: '<div xmlns="http://www.w3.org/1999/xhtml"><table class="hapiPropertyTable"><tbody><tr><td>Identifier</td><td>EXT1234567</td></tr></tbody></table></div>',
    },
    identifier: [
      {
        use: "official",
        value: "EXT1234567",
      },
    ],
  },
  {
    resourceType: "Patient",
    id: "898fa28e-5117-4b92-947a-c0a4a5622b4a",
    meta: {
      versionId: "1",
      lastUpdated: "2020-06-12T16:44:27.046+00:00",
      source: "#Kss3rsHRUtgUB18e",
    },
    text: {
      status: "generated",
      div: '<div xmlns="http://www.w3.org/1999/xhtml"><div class="hapiHeaderText">DevDays <b>PATIENT </b></div><table class="hapiPropertyTable"><tbody><tr><td>Date of birth</td><td><span>20 November 2019</span></td></tr></tbody></table></div>',
    },
    name: [
      {
        use: "official",
        family: "Patient",
        given: ["DevDays"],
      },
    ],
    gender: "unknown",
    birthDate: "2019-11-20",
  },
  {
    resourceType: "Patient",
    id: "1202213",
    meta: {
      versionId: "1",
      lastUpdated: "2020-06-12T16:34:45.441+00:00",
      source: "#emGMvlOkhVbIhOhL",
    },
    text: {
      status: "generated",
      div: '<div xmlns="http://www.w3.org/1999/xhtml"><div class="hapiHeaderText">Peter James <b>CHALMERS </b></div><table class="hapiPropertyTable"><tbody><tr><td>Identifier</td><td>56789</td></tr><tr><td>Date of birth</td><td><span>05 June 2010</span></td></tr></tbody></table></div>',
    },
    identifier: [
      {
        system: "http://hapi.fhir.org/baseDstu3/mrn",
        value: "56789",
      },
    ],
    name: [
      {
        family: "Chalmers",
        given: ["Peter", "James"],
      },
    ],
    telecom: [
      {
        system: "phone",
        value: "(03) 5555 4567",
        use: "work",
      },
      {
        system: "email",
        value: "peter@epic.com",
      },
    ],
    gender: "male",
    birthDate: "2010-06-05",
  },
  {
    resourceType: "Patient",
    id: "7a11fc4f-08e3-4f20-a7a0-126a194e9f92",
    meta: {
      versionId: "1",
      lastUpdated: "2020-06-12T16:44:44.723+00:00",
      source: "#67szuO0HL5SnHyC2",
    },
    text: {
      status: "generated",
      div: '<div xmlns="http://www.w3.org/1999/xhtml"><div class="hapiHeaderText">DevDays <b>PATIENT </b></div><table class="hapiPropertyTable"><tbody><tr><td>Date of birth</td><td><span>20 November 2019</span></td></tr></tbody></table></div>',
    },
    name: [
      {
        use: "official",
        family: "Patient",
        given: ["DevDays"],
      },
    ],
    gender: "unknown",
    birthDate: "2019-11-20",
  },
  {
    resourceType: "Patient",
    id: "3fcf48c3-9bff-4c30-9262-22b584837bef",
    meta: {
      versionId: "1",
      lastUpdated: "2020-06-12T16:31:55.190+00:00",
      source: "#r7jdPTdT874EJYJL",
    },
    text: {
      status: "generated",
      div: '<div xmlns="http://www.w3.org/1999/xhtml"><div class="hapiHeaderText">DevDays <b>PATIENT </b></div><table class="hapiPropertyTable"><tbody><tr><td>Date of birth</td><td><span>20 November 2019</span></td></tr></tbody></table></div>',
    },
    name: [
      {
        use: "official",
        family: "Patient",
        given: ["DevDays"],
      },
    ],
    gender: "unknown",
    birthDate: "2019-11-20",
  },
  {
    resourceType: "Patient",
    id: "1202246",
    meta: {
      versionId: "1",
      lastUpdated: "2020-06-12T19:33:58.726+00:00",
      source: "#U1AXqfmXulFa4VmA",
    },
    text: {
      status: "generated",
      div: '<div xmlns="http://www.w3.org/1999/xhtml"><table class="hapiPropertyTable"><tbody><tr><td>Date of birth</td><td><span>13 October 1972</span></td></tr></tbody></table></div>',
    },
    gender: "male",
    birthDate: "1972-10-13",
  },
  {
    resourceType: "Patient",
    id: "bc059161-ade6-44e5-aaeb-7e71c5660fcb",
    meta: {
      versionId: "1",
      lastUpdated: "2020-06-12T16:45:32.911+00:00",
      source: "#8kNHLhnDibBtYmVu",
    },
    text: {
      status: "generated",
      div: '<div xmlns="http://www.w3.org/1999/xhtml"><div class="hapiHeaderText">DevDays <b>PATIENT </b></div><table class="hapiPropertyTable"><tbody><tr><td>Date of birth</td><td><span>20 November 2019</span></td></tr></tbody></table></div>',
    },
    name: [
      {
        use: "official",
        family: "Patient",
        given: ["DevDays"],
      },
    ],
    gender: "unknown",
    birthDate: "2019-11-20",
  },
  {
    resourceType: "Patient",
    id: "1202243",
    meta: {
      versionId: "1",
      lastUpdated: "2020-06-12T19:32:28.947+00:00",
      source: "#aMbnWNGfIE2zelI0",
    },
    text: {
      status: "generated",
      div: '<div xmlns="http://www.w3.org/1999/xhtml"><table class="hapiPropertyTable"><tbody><tr><td>Date of birth</td><td><span>13 October 1972</span></td></tr></tbody></table></div>',
    },
    gender: "male",
    birthDate: "1972-10-13",
  },
  {
    resourceType: "Patient",
    id: "1202245",
    meta: {
      versionId: "1",
      lastUpdated: "2020-06-12T19:33:28.831+00:00",
      source: "#Nrxns35IVkofsH8r",
    },
    text: {
      status: "generated",
      div: '<div xmlns="http://www.w3.org/1999/xhtml"><table class="hapiPropertyTable"><tbody><tr><td>Date of birth</td><td><span>13 October 1972</span></td></tr></tbody></table></div>',
    },
    gender: "male",
    birthDate: "1972-10-13",
  },
] as any;
